/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.awt.FlowLayout;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author a1602020
 */
public class searchLog extends javax.swing.JFrame {

    /** Creates new form searchLog */
    public searchLog() {
        initComponents();
        setTitle("Pesquisa de Logs");
        setSize(400, 400);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        JLabel labelBusca = new JLabel("Filtrar por:");
        labelBusca.setBounds(20, 0, 120, 10);
        add(labelBusca);
        
        JRadioButton rbMoto = new JRadioButton("Motorista");
        rbMoto.setActionCommand("Motorista");
        rbMoto.setSelected(true);

        JRadioButton rbVeic = new JRadioButton("Veículo");
        rbVeic.setActionCommand("Veículos");

        JRadioButton rbDest = new JRadioButton("Destino");
        rbDest.setActionCommand("Destino");

        //Group the radio buttons.
        ButtonGroup group = new ButtonGroup();
        group.add(rbMoto);
        group.add(rbVeic);
        group.add(rbDest);
        
        setLayout( new FlowLayout() );

        add(rbMoto);
        add(rbVeic);
        add(rbDest);
        
        /*if(rbMoto.isSelected()){
            JLabel labelBuscar = new JLabel("Informe o CPF");
            labelBuscar.setBounds(20, 40, 100, 20);
            add(labelBuscar);

            JTextField tfBusca = new JTextField();
            tfBusca.setSize(110,55);
            tfBusca.setLocation(20, 30);
            add(tfBusca);

            JButton buttonBusca = new JButton("Buscar");
            buttonBusca.setSize(90,30);
            buttonBusca.setLocation(140, 67);
            add(buttonBusca);
        }*/

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
